# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('image', models.ImageField(upload_to=b'polls/static/image')),
                ('place_for_service_text', models.CharField(max_length=200)),
                ('location_text', models.CharField(max_length=200)),
                ('description_text', models.TextField()),
                ('price_start_number', models.IntegerField(default=0)),
                ('price_end_number', models.IntegerField(default=1)),
            ],
        ),
    ]
