# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesetable',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
