# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caterlist', '0003_auto_20160210_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodImage', models.ImageField(upload_to=b'caterlist/static')),
                ('foodImage_detail', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SetMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setMenu_number', models.CharField(max_length=5)),
                ('setMenu_name', models.CharField(max_length=100)),
                ('setMenu_detail', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chinesetable',
            name='image',
            field=models.ImageField(upload_to=b'caterlist/static'),
        ),
        migrations.AlterField(
            model_name='chinesetable',
            name='location_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chinesetable',
            name='place_for_service_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chinesetable',
            name='title_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='setmenu',
            name='chinesetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caterlist.ChineseTable'),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='chinesetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caterlist.ChineseTable'),
        ),
    ]
