# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterlist', '0004_auto_20160210_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmenu',
            name='setMenu_price',
            field=models.IntegerField(default=1),
        ),
    ]
